// <auto-generated />
namespace Events.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateisAnontoTrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateisAnontoTrue));
        
        string IMigrationMetadata.Id
        {
            get { return "202204201319327_updateisAnontoTrue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
