// <auto-generated />
namespace Events.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateModeltoPostAnon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateModeltoPostAnon));
        
        string IMigrationMetadata.Id
        {
            get { return "202204201206280_updateModeltoPostAnon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
